### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by codingjoe** [Thermondo/python-package-template#1]
All packages should contain a license by default, since our code is open source unless it is a USP or contains IP.

See also our [open source guide](https://thermondo.github.io/team/open-source.html) for licensing information.

Our default license type is Apache 2.

**Comment by fidelitas** [comment]
That seems to be done, isn't it?

**Comment by Ashlett** [comment]
@fidelitas I think you're mixing up this package (the template) with the package that it creates.
